"use client";   
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({                                                                                                                                            
  children,                                                                                                                                                                     
}: { children: React.ReactNode }) {                                                                                                                                             
  useEffect(() => {                                                                                                                                                             
    if ("serviceWorker" in navigator) {                                                                                                                                         
      navigator.serviceWorker.register("/sw.js");                                                                                                                               
    }                                                                                                                                                                           
  }, []);                                                                                                                                                                       
                                                                                                                                                                                
  return (                                                                                                                                                                      
    <html lang="es">                                                                                                                                                            
      <body>{children}</body>                                                                                                                                                   
    </html>                                                                                                                                                                     
  );                                                                                                                                                                            
}   